FROM nvidia/cuda:12.1.1-devel-ubuntu20.04

ENV TZ=US/Pacific
RUN echo 'APT::Sandbox::User "root";' | tee -a /etc/apt/apt.conf.d/10sandbox
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && \
    apt-get install -y libgtk2.0-dev && \
    apt-get install -y wget bzip2 ca-certificates curl git vim tmux g++ gcc build-essential cmake checkinstall gfortran libjpeg8-dev libtiff5-dev pkg-config yasm libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev libv4l-dev qt5-default libgtk2.0-dev libtbb-dev libatlas-base-dev libfaac-dev libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev libopencore-amrwb-dev x264 v4l-utils libprotobuf-dev protobuf-compiler libgoogle-glog-dev libgflags-dev libgphoto2-dev libhdf5-dev doxygen libflann-dev libboost-all-dev proj-data libproj-dev libyaml-cpp-dev cmake-curses-gui libzmq3-dev freeglut3-dev

SHELL ["/bin/bash", "--login", "-c"]

RUN cd / && wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    /bin/bash /miniconda.sh -b -p /opt/conda &&\
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh &&\
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc &&\
    /bin/bash -c "source ~/.bashrc" && \
    /opt/conda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    /opt/conda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    /opt/conda/bin/conda update -n base -c defaults conda -y

COPY docker/environment_cuda12.yml /tmp/environment_cuda12.yml

RUN /opt/conda/bin/conda install -n base conda-libmamba-solver && \
    /opt/conda/bin/conda config --set solver libmamba

RUN /opt/conda/bin/conda env create -f /tmp/environment_cuda12.yml && \
    /opt/conda/bin/conda clean -afy

ENV PATH $PATH:/opt/conda/envs/go/bin

RUN conda activate go

RUN conda init bash &&\
    echo "conda activate go" >> ~/.bashrc

# Copy external packages for installation
COPY external /workspace/gotrack/external
WORKDIR /workspace/gotrack

# Install bop_toolkit
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate go && \
    cd external/bop_toolkit && \
    pip install -e . && \
    cd ../..

# Install dinov2 (skipping dependency checks to avoid torch version conflicts)
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate go && \
    cd external/dinov2 && \
    pip install -e . --no-deps && \
    pip install omegaconf fvcore iopath submitit && \
    cd ../..

ENV SHELL=/bin/bash
RUN ln -sf /bin/bash /bin/sh
